project_name: base16-builder-go
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
-
  image_templates:
  - "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}"
  - "ghcr.io/tinted-theming/base16-builder-go:v{{ .Major }}.{{ .Minor }}"
  - "ghcr.io/tinted-theming/base16-builder-go:latest"
  extra_files:
  - entrypoint.sh
archives:
- format: binary
  replacements:
    amd64: x86_64
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
